name: Deploy awsl
on:
  workflow_dispatch:

jobs:
  deployment:
    name: Deploy awsl
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "awsl-project/helm-awsl"
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Create secret
        run: |
          mkdir -p $HOME/.kube/
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          echo "${{ secrets.HELM_SECRET }}" > templates/secret.yaml

      - name: Install helm
        run: |
          cd /tmp
          curl -LO https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
          tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
          mv linux-amd64/helm /usr/local/bin/helm
          helm version

      - name: Lint helm charts
        run: helm lint .

      - name: Diff
        run: |
          helmlist=`helm list -n awsl`
          if [ ! -z "$helmlist" ]
          then
              echo $helmlist
              helm plugin install https://github.com/databus23/helm-diff
              helm diff upgrade awsl -n awsl .
          else
              echo "No helm history"
          fi

      - name: Deploy
        run: |
          helm upgrade --install awsl --timeout 10m -n awsl .

      - name: CleanUp
        run: |
          rm $HOME/.kube/config
          rm templates/secret.yaml
